name: chatverse
description: "A standalone AI-powered chat and voice translation app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies for Chatverse
dependencies:
  flutter:
    sdk: flutter

  # --- Core Dependencies ---
  # For AI translation via Gemini
  google_generative_ai: ^0.4.3 # This seems up-to-date for now

  # For iOS style icons
  cupertino_icons: ^1.0.8

  # --- Dependencies for On-Device Voice Translation ---

  # For requesting microphone permissions (needed by STT)
  permission_handler: ^11.4.0 # Updated to latest stable

  # For accessing native Speech-to-Text (STT)
  speech_to_text: ^7.0.0 # Updated to latest stable (should fix the error)

  # For accessing native Text-to-Speech (TTS)
  flutter_tts: ^4.0.2 # This seems up-to-date for now

  # For getting files from Share Sheet
  receive_sharing_intent: ^1.6.0


  # --- State Management (Recommended - Uncomment your choice later if needed) ---
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter for code analysis
  flutter_lints: ^5.0.0 # Updated to latest major version

# Flutter specific configurations
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700